//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch EasyGraph.rc
//
#define IDB_CLASS_VIEW                  1
#define IDB_CLASS_VIEW_24               2
#define IDB_EXPLORER_24                 3
#define IDB_FILE_VIEW                   4
#define IDB_FILE_VIEW_24                5
#define IDB_MENU_IMAGES_24              6
#define IDB_PROPERTIES_HC               7
#define IDB_SORT_24                     8
#define IDB_SPLASH                      9
#define IDB_TOOLBAR_HC                  10
#define IDC_CHART                       100
#define IDC_CHART_DATE                  101
#define IDC_CHART_LINE                  102
#define IDC_CHART_TITLE                 103
#define IDC_FORM                        104
#define IDC_FORM_TITLE                  105
#define IDC_GROUP                       106
#define IDC_GROUP_TITLE                 107
#define IDC_SCROLLBAR2                  108
#define IDC_SCROLLBAR_HORZ              109
#define IDC_SCROLLBAR_VERT              110
#define IDC_TITLE                       111
#define IDC_TOTALIZER                   112
#define IDC_TOTALIZER_COMBO             113
#define IDC_TOTALIZER_DATE              114
#define IDC_TOTALIZER_KEYSELECT         115
#define IDC_TOTALIZER_LINE              116
#define IDC_TOTALIZER_TITLE             117
#define IDC_SCROLLBAR1                  118
#define IDD_ABOUTBOX                    200
#define IDD_CHART                       201
#define IDD_FORM                        202
#define IDD_GROUP                       203
#define IDD_TEST                        204
#define IDD_TOTALIZER                   205
#define IDI_CLASS_VIEW                  300
#define IDI_CLASS_VIEW_HC               301
#define IDI_FILE_VIEW                   302
#define IDI_FILE_VIEW_HC                303
#define IDI_OUTPUT_WND                  304
#define IDI_OUTPUT_WND_HC               305
#define IDI_PROPERTIES_WND              306
#define IDI_PROPERTIES_WND_HC           307
#define IDP_OLE_INIT_FAILED             308
#define IDR_EXPLORER                    309
#define IDR_EasyGraphTYPE               310
#define IDR_MAINFRAME                   311
#define IDR_MAINFRAME_256               312
#define IDR_MENU_IMAGES                 313
#define IDR_MENU_VIEW                   314
#define IDR_OUTPUT_POPUP                315
#define IDR_POPUP_EDIT                  316
#define IDR_POPUP_EXPLORER              317
#define IDR_POPUP_SORT                  318
#define IDR_PROPERTIES                  319
#define IDR_SORT                        320
#define IDR_THEME_MENU                  321
#define IDS_BUILD_TAB                   400
#define IDS_CALENDAR_VIEW               401
#define IDS_EDIT_MENU                   402
#define IDS_EXPLORER                    403
#define IDS_FILE_VIEW                   404
#define IDS_FILE_VIEW2                  405
#define IDS_GRAFIKSELECT_VIEW           406
#define IDS_OUTPUT_WND                  407
#define IDS_PROPERTIES_WND              408
#define IDS_STATUS_PANE1                409
#define IDS_STATUS_PANE2                410
#define IDS_STRING101                   411
#define IDS_TOOLBAR_CUSTOMIZE           412
#define IDS_TOOLBAR_STANDARD            413
#define ID_CHART_COPY                   500
#define ID_CHART_EXPORT                 501
#define ID_CLASS_ADD_MEMBER_FUNCTION    502
#define ID_CLASS_ADD_MEMBER_VARIABLE    503
#define ID_CLASS_DEFINITION             504
#define ID_CLASS_PROPERTIES             505
#define ID_COLOR_LABEL                  506
#define ID_COLOR_THEME_COMBO            507
#define ID_DARK_THEME                   508
#define ID_DOSESELECT_COMBO             509
#define ID_DUMMY_COMPILE                510
#define ID_EXPAND_ALL                   511
#define ID_NEW_FOLDER                   512
#define ID_OPEN                         513
#define ID_OPEN_WITH                    514
#define ID_PROPERTIES                   515
#define ID_PROPERTIES1                  516
#define ID_PROPERTIES2                  517
#define ID_SET_STYLE                    518
#define ID_SORTING_GROUPBYTYPE          519
#define ID_SORTING_SORTALPHABETIC       520
#define ID_SORTING_SORTBYACCESS         521
#define ID_SORTING_SORTBYTYPE           522
#define ID_SORTPROPERTIES               523
#define ID_SORT_MENU                    524
#define ID_STATUSBAR                    525
#define ID_STATUSBAR_PANE1              526
#define ID_STATUSBAR_PANE2              527
#define ID_TOOLBAR_VIEW                 528
#define ID_TOOLS_MACRO                  529
#define ID_VIEW_APPLOOK_OFF_2003        530
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   531
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  532
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   533
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 534
#define ID_VIEW_APPLOOK_OFF_XP          535
#define ID_VIEW_APPLOOK_VS_2005         536
#define ID_VIEW_APPLOOK_VS_2008         537
#define ID_VIEW_APPLOOK_WINDOWS_7       538
#define ID_VIEW_APPLOOK_WIN_2000        539
#define ID_VIEW_APPLOOK_WIN_XP          540
#define ID_VIEW_BACK                    541
#define ID_VIEW_CALENDAR                542
#define ID_VIEW_CUSTOMIZE               543
#define ID_VIEW_DOSESELECT              544
#define ID_VIEW_FORWARD                 545
#define ID_VIEW_OUTPUTWND               546
#define ID_VIEW_PROPERTIESWND           547
#define ID_VIEW_UP                      548
#define ID_WINDOW_MANAGER               549

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        13
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         119
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
